### ISSUE TITLE
[PATCH NOT WORKING] Red Dead Redemption CUSA36843 

### ISSUE THREAD

**Issue by sandirickyroy** [GoldHEN/GoldHEN_Patch_Repository#106]
The patches are not working for Red Dead Redemption CUSA36843 as it is stated as "mask"

**Comment by LupusEtFlos** [comment]
They work fine. Make sure you enabled game_patch.prx for the game in your plugins.ini in /data/GoldHEN

**Comment by sandirickyroy** [comment]
> They work fine. Make sure you enabled game_patch.prx for the game in your plugins.ini in /data/GoldHEN

Thanks mahn. It worked.
