### ISSUE TITLE
[Patch Request] Far Cry 3 CUSA10326 1.02 60FPS

### ISSUE THREAD

**Issue by SatoshiGuacamole** [GoldHEN/GoldHEN_Patch_Repository#25]
I'm starting a new playthrough of Far Cry 3 but this time on my PS4 Pro. I've seen on your blog that you already have discovered how to unlock 60FPS for this title but it's not yet available here.

I think I need to figure out the address of the patch so that I can create the patch myself but not yet sure how to approach.

Could you please look if it's possible to add the patch to this repository? Or could somebody explain how I can find the correct address?

Edit:

Tried but failed. This will stop the game from loading:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Patch>
    <TitleID>
        <ID>CUSA10326</ID>
    </TitleID>
    <Metadata Title="Far Cry 3"
              Name="60 FPS Unlock"
              Author="SatoshiGuacamole"
              PatchVer="1.0"
              AppVer="01.02"
              AppElf="eboot.bin">
        <PatchList>
            <Line Type="bytes" Address="0x01a4ac7e" Value="00"/>
        </PatchList>
    </Metadata>
</Patch>
```

**Comment by SatoshiGuacamole** [comment]
I may have found the address but it looks like it's in an incorrect format: 1A4AC7Eh. How can I convert this?

**Comment by SatoshiGuacamole** [comment]
Tried but failed. This will stop the game from loading:

```
<?xml version="1.0" encoding="utf-8"?>
<Patch>
    <TitleID>
        <ID>CUSA10326</ID>
    </TitleID>
    <Metadata Title="Far Cry 3"
              Name="60 FPS Unlock"
              Author="SatoshiGuacamole"
              PatchVer="1.0"
              AppVer="01.02"
              AppElf="eboot.bin">
        <PatchList>
            <Line Type="bytes" Address="0x01a4ac7e" Value="00"/>
        </PatchList>
    </Metadata>
</Patch>

```

**Comment by illusion0001** [comment]
Send eboot to my email. [illusion3185@gmail.com](mailto:illusion3185@gmail.com)

**Comment by ismalopese** [comment]
I don't know for sure on pro, but at least on the normal ps4 fliprate remover works just fine for me.

**Comment by SatoshiGuacamole** [comment]
@ismalopese Gave it ago and sadly does not work, the game averages at 33fps in menu and in game.

**Comment by SatoshiGuacamole** [comment]
Having bad luck, 0x01e3082e throws an error upon booting the game.

**Comment by nedix** [comment]
So 0x01e3082e is as good as I can come up with but the following patch stops with error code CE-34878-0​ which seems commonly associated with corrupt disks.

```xml
<?xml version="1.0" encoding="utf-8"?>
<Patch>
    <TitleID>
        <ID>CUSA10326</ID>
    </TitleID>
    <Metadata Title="Far Cry 3"
              Name="60 FPS Unlock"
              Author="SatoshiGuacamole"
              PatchVer="1.0"
              AppVer="01.02"
              AppElf="eboot.bin">
        <PatchList>
            <Line Type="bytes" Address="0x01e3082e" Value="00"/>
        </PatchList>
    </Metadata>
</Patch>
```

I also tried fliprate remover and force 1080p display plugins

```ini
[CUSA10326]
/data/GoldHEN/plugins/fliprate_remover.prx
/data/GoldHEN/plugins/force_1080p_display.prx
```

but the framerate remains on 33fps and I would love some second opinion on the address lookup I did.

This is the change that should be made:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/2658411/228375374-d2fb87b5-ba96-4a6f-a735-8df4d7eca415.png">(https://illusion0001.com/_patch/FryCry3-Orbis/)

**Comment by SatoshiGuacamole** [comment]
So 0x01e3082e is as good as I can come up with but the following patch stops with error code CE-34878-0​ which seems commonly associated with corrupt disks.

```xml
<?xml version="1.0" encoding="utf-8"?>
<Patch>
    <TitleID>
        <ID>CUSA10326</ID>
    </TitleID>
    <Metadata Title="Far Cry 3"
              Name="60 FPS Unlock"
              Author="SatoshiGuacamole"
              PatchVer="1.0"
              AppVer="01.02"
              AppElf="eboot.bin">
        <PatchList>
            <Line Type="bytes" Address="0x01e3082e" Value="00"/>
        </PatchList>
    </Metadata>
</Patch>
```

I also tried fliprate remover and force 1080p display plugins

```ini
[CUSA10326]
/data/GoldHEN/plugins/fliprate_remover.prx
/data/GoldHEN/plugins/force_1080p_display.prx
```

but the framerate remains on 33fps and I would love some second opinion on the address lookup I did.

This is the change that should be made:

![image](https://user-images.githubusercontent.com/103341519/228376128-984a602a-f5c1-4145-9ce5-44c3fb721134.png)
(https://illusion0001.com/_patch/FryCry3-Orbis/)

**Comment by illusion0001** [comment]
try
```xml
<?xml version="1.0" encoding="utf-8"?>
<Patch>
    <TitleID>
        <ID>CUSA10326</ID>
    </TitleID>
    <Metadata Title="Far Cry 3"
              Name="60 FPS Unlock"
              Author="illusion"
              PatchVer="1.0"
              AppVer="01.02"
              AppElf="eboot.bin">
        <PatchList>
            <Line Type="bytes" Address="0x01e2c82d" Value="be00000000"/>
        </PatchList>
    </Metadata>
</Patch>
```

**Comment by SatoshiGuacamole** [comment]
With fliprate or the above patch 33-35fps in-game, 60fps during loading. Even if I set my console's resolution to 1080p in settings there is no increase in FPS so game likely always runs on that resolution. Without anything applied the game runs locked to 30fps while loading and in-game.

Too bad, had great results with Crysis + fliprate remover and 1080p display, but for this game I think we are just dealing with a terrible port (also rifle sounds are broken, healing animations are stripped).

Thanks for the effort anyways!

**Comment by illusion0001** [comment]
Cpu limited, not surprised
