### ISSUE TITLE
[Request] Sekiro: Shadows Die Twice (CUSA13801)

### ISSUE THREAD

**Issue by oneohthree** [GoldHEN/GoldHEN_Patch_Repository#30]
Is there any chance to have support for Sekiro: Shadows Die Twice, release CUSA13801?

Thank you

**Comment by illusion0001** [comment]
rename to `CUSA13801.xml` and try
[CUSA13801.xml.txt](https://github.com/GoldHEN/GoldHEN_Patch_Repository/files/11238100/CUSA13801.xml.txt)

**Comment by oneohthree** [comment]
> rename to `CUSA13801.xml` and try [CUSA13801.xml.txt](https://github.com/GoldHEN/GoldHEN_Patch_Repository/files/11238100/CUSA13801.xml.txt)

I forgot to mention I tried doing this. It works on PS4 Pro consoles, but the game crashed on a slim I tested on once.

These are the checksums of the eboot (v1.06) I have:

md5sum: `477cffac16abe41fa569adbd12e19150`
sha1sum: `dbe50168654931ee4fcf7c6c5e7472a5571a3b6c`

**Comment by illusion0001** [comment]
Can you send eboot to my email `illusion3185@gmail.com`

**Comment by oneohthree** [comment]
Just sent it.

**Comment by illusion0001** [comment]
@oneohthree Can you tell me which patch is crashing on Base PS4?

**Comment by illusion0001** [comment]
Should be fixed in #36

**Comment by oneohthree** [comment]
> @oneohthree Can you tell me which patch is crashing on Base PS4?

Well, I no longer have access to the base PS4, but it crashed activating the resolution patch.

**Comment by oneohthree** [comment]
> @oneohthree Can you tell me which patch is crashing on Base PS4?

Well, I no longer have access to the base PS4, but it crashed activating the resolution patch when I tried.
