### ISSUE TITLE
[ PATCH REQUEST ] God of War Ragnarok [CUSA34386] - 60 Patch

### ISSUE THREAD

**Issue by JustFrenchToast** [GoldHEN/GoldHEN_Patch_Repository#42]
I was curious as to if it would be possible to create a patch for God of War Ragnarok - CUSA34386 (Game Version 4.02) to be able to run at 60fps on the PS4 Pro. There also may need to be another subsequent patch to lower resolution to be able to achieve 60fps. Thank you :)

**Comment by illusion0001** [comment]
Fixed by #48
