### ISSUE TITLE
Hogwarts Legacy [CUSA12771] 

### ISSUE THREAD

**Issue by Corpse00** [GoldHEN/GoldHEN_Patch_Repository#57]
Can’t apply any of the hogwarts legacy patches.. also the game version on goldhen cheat manager shows as "mask" and not the actual game V1.03 version that i have

**Comment by illusion0001** [comment]
Update your plugins

**Comment by yogodweed** [comment]
I try manually add cusa number  inside the update cheat patch any file with number add beside the exist use" , " use note pad or any edited text to any file the you see the list of "cusa numbers " enjoy!!
