### ISSUE TITLE
[ PATCH REQUEST ] Armored Core VI: Fires of Rubicon

### ISSUE THREAD

**Issue by lowburger** [GoldHEN/GoldHEN_Patch_Repository#85]
Hi,

May you investigate Armored Core VI for some patch? Here we have usual FromSoftware games problem: framepacing bad, unlocked frame in PS4 Pro but too high res and so on...

Thx!

**Comment by illusion0001** [comment]
Fixed in #88

**Comment by gut5** [comment]
Could this be updated for 1.05 please?
